python3: make it the provider for /usr/bin/python
Reason for this is the underlying problem that in poky /usr/bin/python is
provided by python2 which isn't built inside my image. Therefore i'm lacking
a provider for it.
sway contributes some nice python scripts i'd like to bundle but they contain
/usr/bin/python shebang and do_package_qa test refuses me to install:

ERROR: sway-1.7-rc1-r0 do_package_qa: QA Issue: /usr/bin/inactive-windows-transparency.py contained in package sway requires /usr/bin/python, but no providers found in RDEPENDS:sway? [file-rdeps]
ERROR: sway-1.7-rc1-r0 do_package_qa: Fatal QA errors were found, failing task.
ERROR: Logfile of failure stored in: /home/flk/build/poky/build-raspi/tmp/work/cortexa72-poky-linux/sway/1.7-rc1-r0/temp/log.do_package_qa.1866287
ERROR: Task (/home/flk/build/poky/meta-wayland/recipes-wlroots/sway/sway_git.bb:do_package_qa) failed with exit code '1'

Since this is more a general issue with installing python scripts i decided not
to use patch or sed to adjust the scripts but make python3 the provider for python
although its more invasive like this.